name: Test

on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run the required tests
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
        
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pre-build image and run make test in dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          cacheFrom: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          push: always
          runCmd: |
            make dep
            make test
    