name: Test

on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pre-build dev container image and push to container registry
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{env.REGISTRY}}/${{github.actor}}/${{env.IMAGE_NAME}}
          cacheFrom: ${{env.REGISTRY}}/${{github.actor}}/${{env.IMAGE_NAME}}
          push: always
