name: Test

on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run the required tests
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
        
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          tags: |
            # Dynamically set the branch name as a prefix
            type=sha,prefix={{branch}}-

      - name: Pre-build image and run make test in dev container
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{steps.meta.outputs.tags}}
          push: always
          runCmd: |
            make dep
            make test
