name: Test

on:
  push:
    branches:
      - main
    
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Dev Container Build and Run Action
        uses: devcontainers/ci@v0.3.1900000348
      
        # Add your build and test steps here
      - name: Run tests
        run: make test